/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chris_triangle_GLLib */

#ifndef _Included_com_chris_triangle_GLLib
#define _Included_com_chris_triangle_GLLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chris_triangle_GLLib
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_chris_triangle_GLLib_init
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_chris_triangle_GLLib
 * Method:    draw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_chris_triangle_GLLib_draw
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
